### ISSUE TITLE
Calculation of a surrounded single in a diagram.

### ISSUE THREAD

**Issue by Ebert-Daniel** [sundmanbo/opencalphad#44]
Dear Professor Bo,

I'm trying to calculate the FeTi phase diagram using the TDB attached. The single phase region appears to be "neglected" even when I set a start equilibrium inside the single phase field and map it separately. I calculated it with our "favorite" thermodynamic software to confirm that we have this phase region. I'm sending both results attached. Would you suggest any way for calculating it with OC?  
I wish you all the best and thank you for your hard work for providing a free software for materials thermodynamics

Best wishes
EA

[feti.txt](https://github.com/sundmanbo/opencalphad/files/4804978/feti.txt)
[feti_bo-phdia_OC.pdf](https://github.com/sundmanbo/opencalphad/files/4804983/feti_bo-phdia_OC.pdf)
![Fe-Ti (TC_calc)- feti_bo](https://user-images.githubusercontent.com/54397165/85140832-223b7c00-b246-11ea-85e2-d34eec133c5c.png)

**Comment by sundmanbo** [comment]
Hi EA

The problem is easy to solve, in your TDB file you must add that the BCC_B2 phase is magnetic.  In TC that is set automatically when the BCC_A2 is magnetic but in OC the treatment of "disordered fraction sets" is different.  Thus add a line
TYPE_DEFINITION M GES A_P_D BCC_B2 MAGNETIC  -1.0    4.00000E-01 !
and add M to the line PHASE BCC_B2 %/M .....

Mapping in OC is sensitive to the start point, best to start at x(ti)=.7 and T=1000 in the miscibility gap for BCC.  You will also need a separate start point to calculate the gamma loop.

Best wishes

Bo
