### ISSUE TITLE
TQ4 parallel-alnipt input file

### ISSUE THREAD

**Issue by jfunicamp** [sundmanbo/opencalphad#50]
Hello, I'm having some trouble running the TQ4 example "parallel-alnipt". I've already compiled the sim1 exacutable but I don't know how the input file is made. Could you please provide a input file example?

**Comment by sundmanbo** [comment]
The sim-alnipt.F90 is the main program, if you compiled and linked it as described in the README file th program should start by asking for an input file.  I provided one with the setup.DAT file
You can edit that if you want to test some other compositions or temperatures.
For simulating some other system you have probably to modify the main program.

**Comment by jfunicamp** [comment]
Hello professor Sundman, thank you for your kind reply. I compiled and linked the program sim-alnipt.F90 with Linksim script,  then the program sim1 asks for the input file. But I couldn't find the file setup.DAT that you cited, what is the path to that file?

**Comment by sundmanbo** [comment]
I see that the README as well as the setup.dat files are missing on Github.
I will update the site but enclose the setup file in this message

Best wishes

Bo Sundman


Den lör 2 okt. 2021 kl 13:29 skrev jfunicamp ***@***.***>:

**Comment by jfunicamp** [comment]
Thanks Professor Sundman, I was able to successfully reproduce the example with the input file you provided. Now I'm going to try to adapt it to my metal alloy. Thank you very much

**Comment by sundmanbo** [comment]
Very nice, be aware that I used mobilities in this example because I do not
really
understand how to convert to diffusion coefficients and mobilities
can be used directly if one knows the gradients in chemical potentials.
But one has to make sure that the amount of atoms in each gridpoint does not
change ... unless one has interstitials and vacancies in a sublattice and
I have not figured out how to handle that.

Another simplification is that I ignore any ordering transformations in the
FCC, there is an L1_0 ordered phase that may become stable but I assume
that does not change the
kinetics, diffusion will occur between nearest neighbour sites, not within
sublattices
(except for interstitials).  It may have a small influence on the chemical
potentials.

If you have problems you are welcome to ask more (but not about kinetics, I
prefer not to
bother with that, although I know the main use of thermodynamics is to
model simulations) and please send me a copy if you publish something.

Best wishes

Bosse


Den lör 2 okt. 2021 kl 17:54 skrev jfunicamp ***@***.***>:

**Comment by jfunicamp** [comment]
Thank you very much for your considerations Professor Sundman, it helped me a lot to understand how the calculations are being done. The use of the product of mobility (in mol/m²/s) by the chemical potential to obtain the mass flow is genious. But I'm still wondering how opencalphad calculates mobility in order to provide the result in units of mol/m²/s, would you have any recommendations of reading about the model?
I built a mobility database for a multicomponent alloy based on MQ parameter of binary systems. The values that opencalphad is providing as mobility are just the diffusion activation energy, which would be in J/mol. Therefore, I don't know what other parameter should be indicated for the calculation to result in the units of mol/m²/s. If you have any tips on this. I greatly appreciate your availability. And if I publish something about it I will gladly send you a copy.

Best regards

**Comment by sundmanbo** [comment]
As I wrote I do not understand how to convert mobilities to diffusion
coefficients, it involves the second derivatives of G (the Darken stability
factor).  In the Al-Ni-Pt example I just set a constant mobility value, the
same for all 3 elements.  In OC (as in TC) the mobilities are the values
stored in the database and DICTRA has a model to transform these to
diffusion coefficients but I have not bothered to implement this, I hope
for someone interested in kinetics to help me.
I think one can use mobilities directly, that would simplify things.  As
long as one does not have vacancies in any sublattice one can use mole
fractions to restrict the number of atoms in each gridpoint (volume
element).  If there is diffusion of C on interstitial sites it is more
complex as vacancies can be created or disappear during the simulation at
each grid point.

You can use my email, ***@***.***, directly.  It is a bit
unnecessary to communicate via github.

Best wishes

Bosse


Den sön 3 okt. 2021 kl 15:09 skrev jfunicamp ***@***.***>:
