### ISSUE TITLE
Waiting time/ Scheil solidification calculation

### ISSUE THREAD

**Issue by Trianex** [sundmanbo/opencalphad#54]
Dear all,
I am trying to build the Scheil solidification curve.
My system (from iron4cd database) in mole fraction:

Fe → 0.577 
C  → 0.24 
Si → 0.095
Ti → 0.088

Following the steps showed on the OpenCalphad tutorial, in which there are examples, I could not perform that calculation. The message appear:

![example_opencalphad](https://github.com/sundmanbo/opencalphad/assets/131229283/8940f225-253b-4846-9e0f-08c35dcb0c9c)

Then, I put more time to run the calculation as the message recommend. In this case, was 3600 seconds. But, the message still appear requesting more waiting time. So, is there an ideal waiting time to put in this kind of calculation?

Greetings

**Comment by Jerry1999** [comment]
Hello,

I tried to repeat your calculation using your compositions and Scheil
solidification in OpenCalphad CAE.
Yes, it shows the same information when plotting Fig12 (even Fig1) since
the Scheil calculation is not done correctly..

You can try to check the error for the calculation.
1) Go to tabWidget "Exec" and uncheck the "Show Console Window";
2) Click button "Run Macro File" again
3) Go to "Results" zone and click "Console results"
4) You may find error message:

Error codes: 4399 0 50

Message: No message assigned


So no Scheil calculation results are available.

You can also check the result file from
C:\OpenCalphad_CAE_0_0_9\Console\temp\fig1.plt and no valid data can be
found.


Best regards,
Chunhui Luo
Developer of OpenCalphad CAE

**Comment by Jerry1999** [comment]
Hello Trianex,

Tried to repeat your calculation using your compositions and Scheil
solidification in OpenCalphad CAE.
Yes, it shows the same information when plotting Fig12 (even Fig1) since
the Scheil calculation is not done correctly..

You can try to check the error for the calculation.
1) Go to tabWidget "Exec" and uncheck the "Show Console Window";
2) Click button "Run Macro File" again
3) Go to "Results" zone and click "Console results"
4) You may find error message:

Error codes: 4399 0 50

Message: No message assigned


So no Scheil calculation results are available.

You can also check the result file from
C:\OpenCalphad_CAE_0_0_9\Console\temp\fig1.plt and no valid data can be
found.


Best regards,
Developer of OpenCalphad CAE

**Comment by Trianex** [comment]
Hi Jerry1999,
Yes, I tried those things you mentioned and saw the same error message as well.
I have tested another compositions without carbon, and it performed correctly.
Seems Scheil calculation results are unavailable when carbon is present.

Regards,
Trianex

**Comment by Jerry1999** [comment]
Hello Trianex,

It is possibel to get correct results (Fig1 and Fig12) using following settings:
1) Type start temperature as 2520 K (Enter)
2) Type Eq temperature as 2503 K (an equilibrium only in the liquid)
3) Type Step as 15

God luck!

**Comment by Trianex** [comment]
Hi Jerry1999,
Thanks! That really worked using your steps.
Just to take note about it, how can I reach out to this kind of solution? I tried different approaches without success.
I saw the fig10, and you recommended parameters that are close to the start transformation temperature of Graphite-A9 and FCC-A1. Seems that a temperature little bit higher and more steps solved the waiting time issue.

**Comment by Jerry1999** [comment]
Hello Trianex,

Two comments:
1) If you check the "Console results", you can find that FCC_A1 appears at 2502.71 (from the listed texts below) and so Eq temperature is set as 2503 K:
--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:... echo: step
Step options? /NORMAL/: ... echo: scheil
   ... the command in full is SCHEIL_GULLIVER                         
Before this command you must have set an alloy composition and calculated
an equilibrium in the liquid and have set an axis with T as variable.
Have you done all that? /NO/: ... echo: Y
The simulation will decrease T and change the liquid composition depending
on the solids formed until there is no liquid stable.
 In step_scheil
 Entering map_startpoint           1

Line   1 from   2.503000E+03 with: LIQUID#1  
 Stable phase at start: LIQUID#1           1
Creating a node at    2502.71 where FCC_A1 appears
Terminating line with    8 equilibria at axis limit   2.5027E+03
 Per cent liquid and T   100.00000000000000        2502.7079307586955     

2) The pre-defined waiting time is only related to your computer hardware and gnuplot execution time. It allows enough time for the OpenCalphad CAE program to draw the gnuplot Fig and embed the drawn Fig into the Results widget. In your case, it is due to missing data in gnuplot file (Fig1 and Fig12).

**Comment by Trianex** [comment]
Hi Jerry1999,
That is enough.
Thank you for your kind help and support.

All the best,
Trianex
